# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'atlas_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'atlas_analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  atlas_analytics:
    +materialized: table
    +database: analytics_{{ (target.name).lower() }}
    01_stage:
      01_raw_staging:
        +schema: raw_staging
        +tags: ["raw_staging"]
    02_core:
      01_primed_staging:
        +schema: primed_staging
        +tags: ["primed_staging", "core"]
      02_raw_vault:
        +schema: raw_vault
        +tags: ["raw_vault", "core"]
    03_presentation:
      01_ssot:
        +schema: ssot
        +tags: ["ssot", "presentation"]
      02_curated:
        +schema: curated
        +tags: ["curated", "presentation"]
      03_reporting:
        +schema: reporting
        +tags: ["reporting", "presentation"]

snapshots:
  atlas_analytics:
    +database: analytics_{{ (target.name).lower() }}
    +schema: raw_staging